### ISSUE TITLE
502 error - NGINX Running, SSL seems OK

### ISSUE THREAD

**Issue by jswiss** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#24]
Hi Jason:

Thanks for the awesome tutorial. I tried applying it to an existing site I was migrating to Digital Ocean, and ran into some problems. Everything was functioning fine, until the last part of adding in NGINX. Now when I go to my site I get a 502 error. As in the title, NGINX seems to be working fine, and the SSL has been issued. I'm not sure where to begin to look for issues, so any help/guidance would be much appreciated!

**Comment by jlengstorf** [comment]
@jswiss It's really hard to say, since there are so many moving parts. If you've already tried the obvious stuff like restarting NGINX, then perhaps try serving a single .txt file to make sure things are configured correctly in NGINX.

You may have better luck in NGINX's support community, honestly, since they'll know far more about the edge cases than I will.

I'm going to close this since it's not directly related to the tutorial. Good luck!
